# config server
SERVER_HOST = '127.0.0.1'
SERVER_PORT = 8081
SERVER_DATA_LENGTH = 1024
SERVER_MAX_THREAD = 100


# config mysql
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_DB = 'app'
MYSQL_USERNAME = 'root'
MYSQL_PASSWORD = 'root'

# config message
MESSAGE_SUCCESS = b'success'
